NewRLWeb/Controllers/TypesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using NewRLWeb.Models;
using NewRLWeb.Package;
using NewRLWeb.Filters;
namespace NewRLWeb.Controllers
{
    public class TypesController : Controller
    {
        private rlwzContext db = new rlwzContext();
        private Logic_Large_type dbltype = new Logic_Large_type();
        private Logic_Small_Type dbstype = new Logic_Small_Type();
        //
        // GET: /Types/
        [CheckLogin]
        public ActionResult List()
        {
            List<Large_type> ltype = dbltype.Search();
            return PartialView(ltype);
        }

        //
        // GET: /Types/Details/5

        public ActionResult Details(string ltype = null)
        {
            //Large_type large_type = db.large_type.Find(id);
            //String ltype = id.L_Type;
            List<Small_Type> stypes = dbstype.Search(ltype);
            if (stypes == null)
            {
                return HttpNotFound();
            }
            ViewBag.LType = ltype;
            return PartialView(stypes);
        }

        //
        // GET: /Types/Create
        [CheckLogin]
        public ActionResult Create()
        {
            return PartialView();
        }

        //
        // POST: /Types/Create

        [HttpPost]
        //[ValidateAntiForgeryToken]
        public ActionResult Create(Large_type large_type)
        {
            if (ModelState.IsValid)
            {
                //db.large_type.Add(large_type);
                //db.SaveChanges();
                if (dbltype.Add(large_type))
                    Response.Write("<script>alert('添加成功')</script>");
                else
                    Response.Write("<script>alert('添加成功')</script>");
                return RedirectToAction("List");
            }

            return PartialView(large_type);
        }
        /// <summary>
        /// 添加小类别
        /// 修改人：夏禹
        /// </summary>
        /// <param name="small_type"></param>
        /// <returns></returns>
        public ActionResult AddSType(string ltype=null)
        {
            List<Small_Type> stypes = dbstype.Search(ltype);
            ViewBag.LType = ltype;
            //if (ltype != null)
            //{               
            //    ViewData["smallType"] = ltype;
            //}         
            return PartialView(stypes);
        }


        public ActionResult Add(Small_Type small_type)
        { 
            //small_type.L_Type =(string)TempData["smallType"];
            //small_type.Retain = 0;
            //if (ModelState.IsValid)
            //{
               
                if (dbstype.Add(small_type))
                    Response.Write("<script>alert('添加成功')</script>");
                else
                    Response.Write("<script>alert('添加失败')</script>");
                return RedirectToAction("List");
            //}
            
            //return PartialView(small_type);
        }
        //
        // GET: /Types/Edit/5

        public ActionResult Edit(int id)
        {
            //Large_type large_type = db.large_type.Find(id);
            Large_type large_type = dbltype.SearchbyID(id);
          
            if (large_type == null)
            {
                return HttpNotFound();
            }
            List<Small_Type> stypes = dbstype.Search(large_type.L_Type);
            ViewBag.ID = large_type.ID;
            ViewBag.Retain = large_type.Retain;
            ViewBag.LType = large_type.L_Type;
            return PartialView(stypes);
        }

        //
        // POST: /Types/Edit/5

        [HttpPost]
        //[ValidateAntiForgeryToken]
        public ActionResult Edit(Large_type large_type)
        {
            //if (ModelState.IsValid)
            //{
            //db.Entry(large_type).State = EntityState.Modified;
            //db.SaveChanges();
            if (dbltype.Update(large_type))
                Response.Write("<script>alert('修改成功')</script>");
            else
                Response.Write("<script>alert('修改失败')</script>");
            //}
            List<Small_Type> stypes = dbstype.Search(large_type.L_Type);
            ViewBag.ID = large_type.ID;
            ViewBag.Retain = large_type.Retain;
            ViewBag.LType = large_type.L_Type;
            return PartialView(large_type);
        }

        //修改小类
        public ActionResult EditSt(int id, byte check)
        {
            Small_Type stype = dbstype.SearchbyID(id);
            dbstype.ChangeRetain(id, check);
            Large_type ltype = dbltype.SearchbyLType(stype.L_Type);
            List<Small_Type> stypes = dbstype.Search(ltype.L_Type);
            ViewBag.ID = ltype.ID;
            ViewBag.Retain = ltype.Retain;
            ViewBag.LType = ltype.L_Type;
            return PartialView("Edit", stypes);
        }
        //
        // GET: /Types/Delete/5

        public ActionResult Delete(string ltype = null)
        {
            List<Small_Type> stypes = dbstype.Search(ltype);
            if (stypes == null)
            {
                return HttpNotFound();
            }
            ViewBag.LType = ltype;
            return PartialView(stypes);
        }

        //
        // POST: /Types/Delete/5

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(string ltype)
        {
            //Large_type large_type = db.large_type.Find(id);
            //db.large_type.Remove(large_type);
            //db.SaveChanges();
            if(dbstype.Delete(ltype) && dbltype.Delete(ltype))
            {
                Response.Write("<script>alert('删除成功！')</script>");
                List<Large_type> largetype = dbltype.Search();
                return PartialView("List",largetype);
            }
            else
            {
                Response.Write("<script>alert('删除失败！')</script>");
                List<Small_Type> stypes = dbstype.Search(ltype);
                ViewBag.LType = ltype;
                return PartialView("Delete",stypes);
            }
        }
        [HttpPost]
        public ActionResult DeleteSt(int id)
        {
            Small_Type stype = dbstype.SearchbyID(id);

            if (dbstype.Delete(id))
                Response.Write("<script>alert('删除成功')</script>");
            else
                Response.Write("<script>alert('删除失败')</script>");
            Large_type ltype = dbltype.SearchbyLType(stype.L_Type);
            List<Small_Type> stypes = dbstype.Search(ltype.L_Type);
            ViewBag.ID = ltype.ID;
            ViewBag.Retain = ltype.Retain;
            ViewBag.LType = ltype.L_Type;
            return PartialView("Edit", stypes);
        }

        public ActionResult DeleteList()
        {
            List<Large_type> ltype = dbltype.SearchCouldDelete();
            return PartialView(ltype);
        }

        public ActionResult MultDelete(FormCollection collection)
        {
            string[] ids = { };
            if (collection.GetValues("checks") != null)
            {
                string strids = collection.GetValue("checks").AttemptedValue;
                ids = strids.Split(',');
                foreach (string getid in ids)
                {
                   dbltype.Delete(Convert.ToInt32(getid));
                }
            }
            return RedirectToAction("DeleteList");
        }
        protected override void Dispose(bool disposing)
        {
            db.Dispose();
            base.Dispose(disposing);
        }
    }
}

NewRLWeb/Views/Types/AddSType.cshtml
@model IEnumerable<NewRLWeb.Models.Small_Type>

@{
    ViewBag.Title = "AddSType";
    //Layout = "~/Views/Shared/_Manage.cshtml";
}
<script>
    //window.onload(a);
    @*function a(){
        var b=  document.getElementById("23").value;
       // var a=@ViewData["smallType"];
        
       //alert(a);
       // document.getElementById("LType").innerHTML =b;
        document.getElementById("L_Type").value = b;
        document.getElementById("form0").submit();
    }*@

</script>
<h2>Add</h2>


    <fieldset>
        <legend>小类</legend>
        <div class="row" >
            @using (Html.BeginForm("Add", "Types", new AjaxOptions { UpdateTargetId = "mainContent", HttpMethod = "Post", InsertionMode = InsertionMode.Replace }))
{
    @*@Html.AntiForgeryToken()
    @Html.ValidationSummary(true)*@
                <br />
    <div class="col-xs-12 col-md-8" style="height: 440px; position: relative;">
        <div class="col-xs-6 col-md-4">
            <div class="editor-label">
                <label>大类名称</label>
            </div>
            <div class="editor-field">
                <input class="form-control" id="L_Type" name="L_Type" readonly="readonly" type="text" value="@ViewBag.LType">
                @*@Html.TextBoxFor(model => model.L_Type, new { @class = "form-control", @readonly = "readonly" })
                @Html.ValidationMessageFor(model => model.L_Type)*@
            </div>
            <br />
            <div class="editor-label">
                @*@Html.LabelFor(model => model.S_Type)*@
                <label>小类名称</label>
            </div>
            <div class="editor-field">
                <input class="form-control" data-val="true" data-val-required="S_Type 字段是必需的。" id="S_Type" maxlength="4" name="S_Type" required="required" type="text" value="">
                @*@Html.TextBoxFor(model => model.S_Type, new { @class = "form-control", @required = "required", @maxlength = "4" })
                @Html.ValidationMessageFor(model => model.S_Type)*@
            </div>
            <br />
            <div class="editor-label">
                <label>是否可删</label>
            </div>
            <div class="editor-field">
                <input checked="checked" data-val="true" data-val-number="字段 是否可删 必须是一个数字。" data-val-range="字段 是否可删 必须在 0 和 1 之间。" data-val-range-max="1" data-val-range-min="0" data-val-required="是否可删 字段是必需的。" id="radio0" name="Retain" type="radio" value="0">否
                &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                <input id="radio1" name="Retain" type="radio" value="1">是
            </div>
        </div>
        @*<input type="button" id="23" value="@ViewData["smallType"]" style="display:none;" />*@
        <p>
            <input type="submit" value="Create" name="Create" @*onclick="a()"*@ style="right: 10%; position: absolute; bottom: 0; " />
        </p>
    </div>
}
            <div class="col-xs-6 col-md-4">
                @if(Model != null)
                {
                    <table class="table table-hover">
                        <tr>
                            <th>小类名称</th>
                            <th>是否可删</th>
                        </tr>
                        @foreach(var item in Model)
                        { 
                        <tr>
                            <td>@Html.DisplayFor(modelItem => item.S_Type)</td>
                            <td>@UIHelper.ShowRetain(item.Retain)</td>
                        </tr>
                        }
                    </table>
                }
            </div>
        </div>
       
    </fieldset>



<div>
    @Html.ActionLink("返回", "List", FormMethod.Get)
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

NewRLWeb/Views/Types/Create.cshtml
@model NewRLWeb.Models.Large_type

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Manage.cshtml";/*2017.2.27 BLM加*/

}


<div style="height: 480px; position: relative;">
    @using (Html.BeginForm("Create", "Types", FormMethod.Post, new { enctype = "multipart/form-data" }))
    {
        @Html.AntiForgeryToken()
        @Html.ValidationSummary(true)

        <fieldset>
            <legend></legend>
            <br />
            <div class="row">
                <div class="col-md-3 col-md-offset-3">
                    <div class="editor-label">
                        @*@Html.LabelFor(model => model.L_Type)*@
                        <label>类别名称</label>
                    </div>
                    <div class="editor-field">
                        @Html.TextBoxFor(model => model.L_Type, new { @class = "form-control", @required = "required", @maxlength = "4" })
                        @Html.ValidationMessageFor(model => model.L_Type)
                    </div>
                </div>
            </div>
            <br /><br />
            <div class="row">
                <div class="col-md-3 col-md-offset-3">
                    <div class="editor-label">
                        @Html.LabelFor(model => model.Retain)
                    </div>
                    <div class="editor-field">
                        @Html.RadioButtonFor(model => model.Retain, 0, new { @id = "radio0", @name = "retain", @checked = "checked" })否
                        &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                        @Html.RadioButtonFor(model => model.Retain, 1, new { @id = "radio1", @name = "retain" })是
                        @Html.ValidationMessageFor(model => model.Retain)
                    </div>
                </div>
            </div>
            <p>
                <input type="submit" value="确定" name="Create" style="right: 17%; position: absolute; bottom: 0; " />
            </p>
        </fieldset>

    }
</div>
<div>
    @Html.ActionLink("返回", "List", FormMethod.Get)
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

NewRLWeb/Views/Types/Delete.cshtml
@model IEnumerable<NewRLWeb.Models.Small_Type>

@{
    ViewBag.Title = "Delete";
}

<h2>删除类别</h2>
<fieldset>
    <legend>确定要删除这个类别么?</legend>
    <div class="row" style="height:480px">
        <div class="col-md-6 col-md-offset-3">
            <div class="editor-label">
                <label>大类名称</label>
            </div>
            <div class="editor-field">
                <input class="form-control" id="L_Type" name="L_Type" readonly="readonly" type="text" value="@ViewBag.LType">
            </div>
            <br />
            @if (Model != null && Model.Count() != 0)
            {
                <table class="table table-hover">
                    <tr>
                        <th>小类名称</th>
                        <th>是否可删</th>
                    </tr>
                    @foreach (var item in Model)
                    {
                        <tr>
                            <td>@Html.DisplayFor(modelItem => item.S_Type)</td>
                            <td>@UIHelper.ShowRetain(item.Retain)</td>
                        </tr>
                    }
                </table>
            }
        </div>
    </div>
    @*<p>
        <input type="submit" value="删除" />
    </p>*@
    <p style="left : 5%; position: absolute; bottom: 0; ">
            <button>@Ajax.ActionLink("删除", "DeleteConfirmed", new { ltype = @ViewBag.LType }, new AjaxOptions { UpdateTargetId = "mainContent", HttpMethod = "Post", InsertionMode = InsertionMode.Replace })</button> |
        </p>
</fieldset>

<p>
    @Html.ActionLink("返回", "List", FormMethod.Get)
</p>

NewRLWeb/Views/Types/DeleteList.cshtml
@model IEnumerable<NewRLWeb.Models.Large_type>

@{
    ViewBag.Title = "DeleteList";
}

<script>
    $("#chkAll").click(function () {
        if (this.checked) {
            $("input[name='checks']").each(function () { this.checked = true; });
        }
        else {
            $("input[name='checks']").each(function () { this.checked = false; });
        }
    });
</script>

<h2>DeleteList</h2>

@*<p>
    @Ajax.ActionLink("Create New", "Create", "Types", new AjaxOptions() { UpdateTargetId = "mainContent", HttpMethod = "Get", OnBegin = "active", InsertionMode = InsertionMode.Replace })
</p>*@
@using (Ajax.BeginForm("MultDelete", "Types", new AjaxOptions { HttpMethod = "Post", UpdateTargetId = "mainContent", InsertionMode = InsertionMode.Replace }))
{
<table border='1' cellspacing="0" cellpadding="0">
    <tr>
        <th>
            <input type="checkbox" id="chkAll" />全选
        </th>
        <th>编号</th>
        <th>@Html.DisplayNameFor(model => model.L_Type)</th>

    </tr>
    @{var i = 0;}
    @foreach (var item in Model)
    {
        i++;
        <tr>
            <td>
                @*@Html.CheckBox("checks", new { value = @ })*@
                <input type="checkbox" id="checks" name="checks" value="@item.ID" />
            </td>
            <td class='onecenter'>
                @i
            </td>
            <td class='onecenter'>
                @Html.DisplayFor(modelItem => item.L_Type)
            </td>
        </tr>
    }   
</table>
    <input type="submit" name="BtnDelete" value="删除" />
}

NewRLWeb/Views/Types/DeleteTable.cshtml
@model NewRLWeb.Package.Logic_Large_type

NewRLWeb/Views/Types/Edit.cshtml
@model IEnumerable<NewRLWeb.Models.Small_Type>

@{
    ViewBag.Title = "Edit";
    //Layout = "~/Views/Shared/_Manage.cshtml";
}
@*
    2017.03.01
    BLM
    修改弹窗
*@
<link rel="stylesheet" href="~/Content/Types/common.css" />
<script type="text/javascript" src="~/Scripts/jquery-formobilwindow.min.js"></script>
<script type="text/javascript">
    var w, h, deleteid;//className;
    function getSrceenWH() {
        w = $(window).width();
        h = $(window).height();
        $('#dialogBg').width(w).height(h);
    }

    window.onresize = function () {
        getSrceenWH();
    }
    $(window).resize();

    $(function () {
        getSrceenWH();
        //显示弹窗
        $("td #delete").click(function () {
            $('#dialogBg').fadeIn(300);
            $(this).next().removeAttr('class').addClass('animated bounceIn').fadeIn();
        });
        $("td #edit").click(function () {
            $('#dialogBg').fadeIn(300);
            $(this).next().removeAttr('class').addClass('animated bounceIn').fadeIn();
        });
        //关闭弹窗
        $('.claseDialogBtn').click(function () {
            $('#dialogBg').fadeOut(300);//, function () {
            $(this).parent().parent().addClass('bounceOutUp').fadeOut();
        });
        $("td div #Save").click(function () {

            var val = $(this).next().next().next(".row").children('input:radio[name="Retain"]:checked').val();
            var SId = $(this).next().next().next().next("#STypeID").val();

            if (val != 1)
                val == 0;
            var postData = { id: SId, check: val };
            var url = "@Url.Action("EditSt","Types")";
            //弹窗关闭2017.03.01 start
            $('#dialogBg').fadeOut(300);
            $(this).parent().parent().addClass('bounceOutUp').fadeOut();
            //弹窗关闭2017.03.01 end
            $.ajax({
                url: url,
                async: false,
                type: "POST",
                data: postData,
                cache: false,
                global: false,
                dataType: 'html',
                error: function () {
                    alert('修改失败！');
                },
                success: function () {
                    alert('修改成功！');
                }
            });

        });
    });
</script>

<h2>Edit</h2>
<fieldset>
    <legend></legend>
    <div class="row" style="min-height:480px">
        <div class="col-md-6 col-md-offset-3">
            @using (Html.BeginForm("Edit", "Types", FormMethod.Post))
            {
                <br />
                <div class="row" style="height: 200px; position: relative">
                    <div class="col-xs-6">
                        <input id="ID" name="ID" required="required" type="hidden" value="@ViewBag.ID" />
                        <div class="editor-label">
                            <label>大类名称</label>
                        </div>
                        <div class="editor-field">
                            <input class="form-control" id="L_Type" name="L_Type" @*readonly="readonly"*@ type="text" value="@ViewBag.LType">
                        </div>
                        <br />
                        <div class="editor-label">
                            <label>是否可删</label>
                        </div>
                        <div class="editor-field">
                            @if (ViewBag.Retain == 0)
                            {
                                <input checked="checked" data-val="true" data-val-number="字段 是否可删 必须是一个数字。" data-val-range="字段 是否可删 必须在 0 和 1 之间。" data-val-range-max="1" data-val-range-min="0" data-val-required="是否可删 字段是必需的。" id="radio0" name="Retain" type="radio" value="0">@:否
                                @:&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                                <input id="radio1" name="Retain" type="radio" value="1">@:是
                    }
                            else
                            {
                                <input data-val="true" data-val-number="字段 是否可删 必须是一个数字。" data-val-range="字段 是否可删 必须在 0 和 1 之间。" data-val-range-max="1" data-val-range-min="0" data-val-required="是否可删 字段是必需的。" id="radio0" name="Retain" type="radio" value="0">@:否
                                @:&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                                <input checked="checked" id="radio1" name="Retain" type="radio" value="1">@:是
                    }
                        </div>
                        <p>
                            <input type="submit" value="Edit" name="Edit" @*onclick="a()"*@ style="right: 10%; position: absolute; bottom: 0; " />
                        </p>
                    </div>
                    <p style="left: 0%; position: absolute; bottom: -20px">
                        @Ajax.ActionLink("添加小类别", "AddSType", "Types", new { ltype = @ViewBag.LType }, new AjaxOptions() { UpdateTargetId = "mainContent", HttpMethod = "Get", OnBegin = "active", InsertionMode = InsertionMode.Replace })
                    </p>
                </div>
                <br />
            }

            @if (Model != null)
            {
                <table class="table table-hover">
                    <tr>
                        <th>小类名称</th>
                        <th>是否可删</th>
                        <th></th>
                    </tr>
                    @foreach (var item in Model)
                    {
                        <tr>
                            <td>@Html.DisplayFor(modelItem => item.S_Type)</td>
                            <td>@UIHelper.ShowRetain(item.Retain)</td>
                            <td>
                                <a id="edit" name="edit">Edit</a>
                                <div id="dialog" class="animated">
                                    <div class="dialogTop">
                                        <label style="float:left">修改此类别？</label>
                                        <a href="javascript:;" class="claseDialogBtn">关闭</a>
                                    </div>
                                    <div class="row" style="height:180px; position: relative">
                                        <br />
                                        @*<button style="right: 25px; position: absolute; bottom: 0; ">@Ajax.ActionLink("保存..", "Editst", new { id = item.ID }, new AjaxOptions() { UpdateTargetId = "mainContent", HttpMethod = "Post", OnBegin = "active", InsertionMode = InsertionMode.Replace })</button>*@
                                        <input type="button" id="Save" name="Save" value="保存" style="width:60px; right: 25px; position: absolute; bottom: 0; " />
                                        <div class="row">
                                            <div class="col-xs-12 col-md-10" style="margin-left:20px">
                                                <label>小类名称</label>
                                                <input class="form-control" id="S_Type" name="S_Type" readonly="readonly" type="text" value="@item.S_Type">

                                            </div>
                                        </div>
                                        <br />
                                        <div class="row" style="margin-left:20px">
                                            <div class="editor-label">
                                                <label>是否可删</label>
                                            </div>
                                            @if (item.Retain == 0)
                                            {
                                                <input id="radio0" name="Retain" type="radio" value="0" checked="checked" />@:否
                                                @:&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                                                <input id="radio1" name="Retain" type="radio" value="1" />@:是
                                            }
                                            else
                                            {
                                                <input id="radio0" name="Retain" type="radio" value="0" />@:否
                                                @:&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                                                <input checked="checked" id="radio1" name="Retain" type="radio" value="1" />@:是
                                        }

                                        </div>
                                        <input type="hidden" id="STypeID" name="ID" value="@item.ID" />
                                    </div>
                                </div>
                                @if (item.Retain == 1)
                                {
                                    @:&nbsp;|
                                    <a id="delete" name="delete">Delete</a>
                                }
                                <div id="dialog" class="animated">
                                    <div class="dialogTop">
                                        <label style="float:left">确定删除此类别？</label>
                                        <a href="javascript:;" class="claseDialogBtn">关闭</a>
                                    </div>
                                    <div class="row" style="height: 180px; position: relative">
                                        <br />
                                        <div class="row" style="margin-left:20px">
                                            <div class="col-xs-12 col-md-10">
                                                <label>小类名称</label>
                                                <input class="form-control" id="S_Type" name="S_Type" readonly="readonly" type="text" value="@item.S_Type">
                                            </div>
                                        </div>
                                        <br />
                                        <button style="right: 25px; position: absolute; bottom: 0; ">@Ajax.ActionLink("删除", "DeleteSt", new { id = item.ID }, new AjaxOptions() { UpdateTargetId = "mainContent", HttpMethod = "Post", OnBegin = "active", InsertionMode = InsertionMode.Replace })</button>
                                    </div>
                                </div>
                            </td>
                        </tr>
                    }
                </table>
                <div id="dialogBg"></div>
            }
        </div>

    </div>

</fieldset>



<div>
    @Html.ActionLink("返回", "List", FormMethod.Get)
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

NewRLWeb/Views/Types/List.cshtml
@model IEnumerable<NewRLWeb.Models.Large_type>

@{
    ViewBag.Title = "List";
    Layout = "~/Views/Shared/_Manage.cshtml";/*2017.2.27 BLM加*/

}
<table class="table table-hover">
    <tr>
        <th>编号</th>
        <th>类别</th>
        <th>@Html.DisplayNameFor(model => model.Retain)</th>
        <th></th>
    </tr>
    @{var i = 0;}
    @foreach (var item in Model)
    {
        i++;
        <tr>
            <td>
                @i
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.L_Type)
            </td>
            <td>@UIHelper.ShowRetain(item.Retain)</td>
            <td>
                @Ajax.ActionLink("编辑", "Edit", "Types", new { id = item.ID }, new AjaxOptions() { UpdateTargetId = "mainContent", HttpMethod = "Get", OnBegin = "active", InsertionMode = InsertionMode.Replace }) |
                @Ajax.ActionLink("添加小类别", "AddSType", "Types", new { ltype = item.L_Type }, new AjaxOptions() { UpdateTargetId = "mainContent", HttpMethod = "Get", OnBegin = "active", InsertionMode = InsertionMode.Replace }) |
                @*@Ajax.ActionLink("Edit", "Edit", "Types", new { id = item.L_Type }, new AjaxOptions() { UpdateTargetId = "mainContent", HttpMethod = "Get", OnBegin = "active", InsertionMode = InsertionMode.Replace }) |*@
                @Ajax.ActionLink("详情", "Details", "Types", new { ltype = item.L_Type }, new AjaxOptions() { UpdateTargetId = "mainContent", HttpMethod = "Get", OnBegin = "active", InsertionMode = InsertionMode.Replace })
                @if (item.Retain == 1)
                {
                    @:| @Ajax.ActionLink("删除", "Delete", "Types", new { ltype = item.L_Type }, new AjaxOptions() { UpdateTargetId = "mainContent", HttpMethod = "Get", OnBegin = "active", InsertionMode = InsertionMode.Replace })
                }
            </td>
        </tr>
    }

</table>

NewRLWeb/Views/Types/Table.cshtml
@model IEnumerable<NewRLWeb.Models.Large_type>

@{
    ViewBag.Title = "List";
}

<h2>List</h2>

<p>
    @Ajax.ActionLink("Create New", "Create", "Types", new AjaxOptions() { UpdateTargetId = "mainContent", HttpMethod = "Get", OnBegin = "active", InsertionMode = InsertionMode.Replace })
</p>
<table border='1' cellspacing="0" cellpadding="0">
    <tr>
        <th>编号</th>
        <th>@Html.DisplayNameFor(model => model.L_Type)</th>

    </tr>
    @{var i = 0;}
    @foreach (var item in Model)
    {
        i++;
        <tr>
            <td class='onecenter'>
                @i
            </td>
            <td class='onecenter'>
                @Html.DisplayFor(modelItem => item.L_Type)
            </td>
            <td class='onecenter'>
                @*@Ajax.ActionLink("Edit", "Edit", "Types", new { id = item.L_Type }, new AjaxOptions() { UpdateTargetId = "mainContent", HttpMethod = "Get", OnBegin = "active", InsertionMode = InsertionMode.Replace }) |*@
                @Ajax.ActionLink("Details", "Details", "Types", new { id = item.L_Type }, new AjaxOptions() { UpdateTargetId = "mainContent", HttpMethod = "Get", OnBegin = "active", InsertionMode = InsertionMode.Replace }) |
                @*@Ajax.ActionLink("Delete", "Delete", "Types", new { id = item.L_Type }, new AjaxOptions() { UpdateTargetId = "mainContent", HttpMethod = "Get", OnBegin = "active", InsertionMode = InsertionMode.Replace }))*@
                @Ajax.ActionLink("添加小类别", "AddSType", "Types", new { id = item.L_Type }, new AjaxOptions() { UpdateTargetId = "mainContent", HttpMethod = "Get", OnBegin = "active", InsertionMode = InsertionMode.Replace }))
            </td>
        </tr>
    }

</table>