NewRLWeb/Controllers/RulesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using NewRLWeb.Models;
using NewRLWeb.Package;
using System.IO;
using NewRLWeb.Filters;
namespace NewRLWeb.Controllers
{
    public class RulesController : Controller
    {
        private rlwzContext db = new rlwzContext();
        private Logic_Rules_Management logic = new Logic_Rules_Management();//zsl 2016.11.30
        //
        // GET: /Rules/

        public ActionResult Index()//zsl 2016.11.30
        {
            Rules_Management rm = new Rules_Management();
            rm = logic.search();
            return View(rm);
        }

        //
        // GET: /Rules/Details/5

        public ActionResult Details(int id = 0)
        {
            Rules_Management rules_management = db.rules_management.Find(id);
            if (rules_management == null)
            {
                return HttpNotFound();
            }
            return View(rules_management);
        }

        //
        // GET: /Rules/Create
        [CheckLogin]
        public ActionResult Create()
        {
            return View();
        }

        //
        // POST: /Rules/Create

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Rules_Management rules_management)
        {
            if (ModelState.IsValid)
            {
                db.rules_management.Add(rules_management);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(rules_management);
        }


        //
        // GET: /Rules/Edit/5


        //修改人：夏禹 2017/1/16
        //案例管理修改
        public ActionResult Edit()
        {
            Rules_Management rules_management = db.rules_management.First();
            if (rules_management == null)
            {
                return HttpNotFound();
            }
            return PartialView(rules_management);
        }

        /// <summary>
        /// 2017.2.24       zsl
        /// </summary>
        /// <param name="rules_management"></param>
        /// <param name="files"></param>
        /// <returns></returns>
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(Rules_Management rules_management,HttpPostedFileBase files)
        {          
            Random r = new Random();
            string filePath = "~/Html/Rules/";
            var realpath = Server.MapPath(filePath);
            Logic_Rules_Management L = new Logic_Rules_Management();
            Response.Write("<script>alert('" + L.save(rules_management, files, realpath) + "')</script>");
            return View("Edit",rules_management);
        }
        //
        // GET: /Rules/Delete/5

        public ActionResult Delete(int id = 0)
        {
            Rules_Management rules_management = db.rules_management.Find(id);
            if (rules_management == null)
            {
                return HttpNotFound();
            }
            return View(rules_management);
        }

        //
        // POST: /Rules/Delete/5

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Rules_Management rules_management = db.rules_management.Find(id);
            db.rules_management.Remove(rules_management);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            db.Dispose();
            base.Dispose(disposing);
        }
    }
}

NewRLWeb/Views/Rules/Create.cshtml
@model NewRLWeb.Models.Rules_Management

@{
    ViewBag.Title = "Create";
}


@using (Html.BeginForm("Create", "Rules", FormMethod.Post))
{
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true)

    <fieldset>
        <legend>条例——新建</legend>
         
        <div class="editor-label">
            @Html.LabelFor(model => model.Author)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Author)
            @Html.ValidationMessageFor(model => model.Author)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Coverage)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Coverage)
            @Html.ValidationMessageFor(model => model.Coverage)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Publicationtime)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Publicationtime)
            @Html.ValidationMessageFor(model => model.Publicationtime)
        </div>

        <p>
            <input type="submit" value="确定" />
        </p>
    </fieldset>
}

<div>
    @Html.ActionLink("返回", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

NewRLWeb/Views/Rules/Delete.cshtml
@model NewRLWeb.Models.Rules_Management

@{
    ViewBag.Title = "Delete";
}


<h3>确定删除该条例?</h3>
<fieldset>
    <legend>Rules_Management</legend>

    <div class="display-label">
        @Html.DisplayNameFor(model => model.Author)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Author)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.Coverage)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Coverage)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.Publicationtime)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Publicationtime)
    </div>
</fieldset>
@using (Html.BeginForm()) {
    @Html.AntiForgeryToken()
    <p>
        <input type="submit" value="Delete" /> |
        @Html.ActionLink("Back to List", "Index")
    </p>
}

NewRLWeb/Views/Rules/Details.cshtml
@model NewRLWeb.Models.Rules_Management

@{
    ViewBag.Title = "Details";
}


<fieldset>
    <legend>条例——详情</legend>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.Author)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Author)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.Coverage)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Coverage)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.Publicationtime)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Publicationtime)
    </div>
</fieldset>
<p>
    @Html.ActionLink("编辑", "Edit", new { id=Model.ID }) |
    @Html.ActionLink("返回", "Index")
</p>

NewRLWeb/Views/Rules/Edit.cshtml
@model NewRLWeb.Models.Rules_Management

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_Manage.cshtml";
}

<h2>条例修改</h2>
<script type="text/javascript">
    var PArray = "";
    var count = 1;
    var coo = count;
    var num=0;
    function showPreview(source) {
        if (!isPicFile(source)) {
            alert("您选择的文件不是一个html文件");
            source.outerHTML = source.outerHTML;//清空file的value
            return false;
        }
    }
    function isPicFile(filename) {
        for (var countFile = 0; filename.files[countFile] != null; countFile++) {
            var file1 = filename.files[countFile];           
            if (file1.type == "text/html") {
                num++;
            }
            else {
                return false;
            }
        }
        return true;
    }
    function clickImage(Img) {
        PArray = PArray + Img.id + "/";
        //alert(PArray);
        Img.style.display = 'none';
    }
    function ClickSub() {
        if (num == 1) {
            document.getElementById("form").submit();
            return true;
        }
        else {
            alert("您还没上传文件！");
            return false;
        }
    }
</script>
@using (Html.BeginForm("Edit", "Rules", FormMethod.Post, new { enctype = "multipart/form-data",id="form"  }))
{
   @Html.AntiForgeryToken();
    @Html.ValidationSummary(true)

    <fieldset>

        @Html.HiddenFor(model => model.ID)

            <div class="editor-label" style="float:left; margin-right:20px;">
                @Html.LabelFor(model => model.Author)
            </div>
        <div class="editor-field" style="float: left; margin-right: 40px;">
            @Html.HiddenFor(model => model.Author)
            <label style="font-weight:normal;">王鹏</label>
        </div>
            <div class="editor-label" style="float: left; margin-right: 20px;">
                @Html.LabelFor(model => model.Coverage)
            </div>

            <div class="editor-label" style="display: none;">
                @Html.LabelFor(model => model.Publicationtime)
            </div>
        
            <div class="editor-field" style="display: none;float:left;">
                @Html.EditorFor(model => model.Publicationtime)
                @Html.ValidationMessageFor(model => model.Publicationtime)
            </div>
            <div id="divMain" style="float:left;">
                <input type="file" id="0img" name="files" multiple="multiple" value="选择文件" onchange="showPreview(this);" />
            </div>
        <input type="button" value="上传" id="sub" onclick="ClickSub()" style="float:left; height:24px; line-height:normal; margin-left:5px" />
    </fieldset>
}

<div style="padding-left: 50px; padding-right: 50px; padding-top: 0px;">
    @{
        string filePath = @Model.Coverage;
        filePath = HttpContext.Current.Server.MapPath(filePath);
        string fileContent = string.Empty;
        var reader = filePath;
        StreamReader sr = new StreamReader(reader, System.Text.Encoding.Default);
        fileContent = sr.ReadToEnd();
    }
    @Html.Raw(fileContent)
    </div>
    @section Scripts {
        @Scripts.Render("~/bundles/jqueryval")
    }

NewRLWeb/Views/Rules/Index.cshtml
@using NewRLWeb.Models
@model Rules_Management

@{
    ViewBag.Title = "Index";
}
        <div style="padding-left: 50px; padding-right: 50px; padding-top: 0px;">
            @{
                string filePath = @Model.Coverage;
                filePath = HttpContext.Current.Server.MapPath(filePath);
                string fileContent = string.Empty;
                var reader = filePath;
                StreamReader sr = new StreamReader(reader, System.Text.Encoding.Default);
                fileContent = sr.ReadToEnd();
            }
            @Html.Raw(fileContent)
            <table>
                <tr>
                    <th>
                        @Model.Author---                    @Model.Publicationtime

                    </th>
                </tr>
            </table>
        </div>
        <div></div>
    @*</div>
</div>*@