NewRLWeb/Models/Academic_Exchange.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel;
using System.Web.Mvc;

namespace NewRLWeb.Models
{
    [DisplayName("学术交流")]
    public class Academic_Exchange
    {
        #region 字段
        [Key]
        //[DisplayName("ID")]
        public int AcademicID { get; set; }

        [Required]
        [MaxLength(20)]
        [DisplayName("学术名称")]
        public string AcademicName { get; set; }

        [Required]
        [MaxLength(100)]
        [DisplayName("摘要")]
        public string Abstract { get; set; }

        [Required]
        [DisplayName("图片")]
        public string PhotoAddress { get; set; }

        [Required]
        [DisplayName("正文")]
        //[Required(ErrorMessage = "您需要填写{0}")]
        public string Coverage { get; set; }

        [DisplayName("开始日期")]
        [Required(ErrorMessage = "您需要选择{0}")]
        [DataType(DataType.DateTime)]
        [DisplayFormat(DataFormatString = "{0:yyyy/MM/dd}", ApplyFormatInEditMode = true)]
        public DateTime BeginTime { get; set; }


        [DisplayName("结束日期")]
        [Required(ErrorMessage = "您需要选择{0}")]
        [DataType(DataType.DateTime)]
        [DisplayFormat(DataFormatString = "{0:yyyy/MM/dd}", ApplyFormatInEditMode = true)]
        public DateTime EndTime { get; set; }
      
        [MaxLength(100)]
        [DisplayName("链接")]
        public string Link { get; set; }
        #endregion
    }
}

NewRLWeb/Controllers/AcademicController.cs
/// <summary>
/// 修改人：周煜
/// 修改内容：1.数据库数据导出
///           2.动态读取相册集照片传入前台
///           
/// </summary>
/// <returns></returns>
/// 
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using NewRLWeb.Models;
using NewRLWeb.Package;
using System.IO;
using System.Text;


namespace NewRLWeb.Controllers
{
    public class AcademicController : Controller
    {
        private rlwzContext db = new rlwzContext();
        private Logic_Academic_Exchange db_academic = new Logic_Academic_Exchange();
        private readonly int pageSize = 10;
        private static int pageCount;
        private static int? choose;

        #region 页面
        //2016.12.3 zsl
        //public ActionResult HomeIndex()
        //{
        //    //List<Academic_Exchange> academic = db_academic.Search();
        //    //pageCount = academic.Count();
        //    ViewBag.PageSize = pageSize;
        //    ViewBag.TotalCount = db.academic_exchange.Count();
        //    return View();
        //}

        //
        // GET: /Academic/
        //public ActionResult Index(int pageIndex = 1)
        public ActionResult HomeIndex(string time)
        {
             List<Academic_Exchange> aratime;
            if (time == null) 
            { 
             aratime = db_academic.Search(); 
             pageCount = aratime.Count();
             ViewBag.Type = -1;
            
            }
            else
            {
                aratime = db_academic.SearchByTypetime(int.Parse(time));
                pageCount = aratime.Count();
                ViewBag.Type = time;
            }
            ViewBag.PageSize = pageSize;
            ViewBag.TotalCount = pageCount;
            //var persons = (from p in db.academic_exchange orderby p.AcademicName descending select p).Skip((pageIndex - 1) * pageSize).Take(pageSize);
            //return PartialView(persons.ToList());
            return PartialView(aratime);

        }
        //邢亚男 从数据库取数据  2017/02/24
        //public ActionResult Index(int? time)
        //{
        //    List<Academic_Exchange> aratime;
        //    aratime = db_academic.SearchByTypetime(time);
        //    pageCount = aratime.Count();
        //    ViewBag.Type = time;
        //    ViewBag.PageSize = pageSize;
        //    ViewBag.TotalCount = pageCount;
        //    return PartialView(aratime);
        //}

        //
        // GET: /Academic/
        public ActionResult Academic_Exchange_View(int id)
        {
            Academic_Exchange academic = db.academic_exchange.Find(id);
            if (academic == null)
            {
                return HttpNotFound();
            }
            return View(academic);
        }
        #endregion

        #region 增 删 改 细节
        //
        // GET: /Academic/Create

        public ActionResult Create()
        {
            return PartialView();
        }
        //
        // POST: /Academic/Create

        [HttpPost]
        [ValidateAntiForgeryToken]
        ///周煜 添加学术交流信息 2016 12 8 待测试
        ///卜令梅 修改 2016 12 8
        public ActionResult Create(Academic_Exchange academic_exchange)
        {
            //if (ModelState.IsValid)
            //{
            var fileHtm = Request.Files["UpLoadHtm"];
            var fileEnc = Request.Files["UpLoadEnc"];
            //if (files == null || files.ContentLength == 0)
            //{
            //    Response.Write("<script>alert('文件上传失败，请重新上传！')</script>");
            //    ViewBag.str = "0";
            //}
            //else
            //{
                if (db_academic.HasSameAcdemicExchange(academic_exchange.AcademicName))
                {
                    ModelState.AddModelError("AcademicName", "已有同名");
                    //Response.Write("<script>alert('添加失败！ ')</script>");
                }
                else if ((academic_exchange.BeginTime.Date.CompareTo(DateTime.Now.Date) > 0) || (academic_exchange.EndTime.Date.CompareTo(DateTime.Now.Date) > 0) || (academic_exchange.BeginTime.Date.CompareTo(academic_exchange.EndTime.Date) > 0))
                {
                    Response.Write("<script>alert('时间选择不正确，请重新上传！')</script>");
                }
                else
                {
                    academic_exchange.Coverage = "rtsh";
                    academic_exchange.PhotoAddress = "fhtrh";
                    if (db_academic.Add(academic_exchange))
                    {
                        academic_exchange = db_academic.SearchbyName(academic_exchange.AcademicName);
                        if (UploadHtm(academic_exchange, fileHtm) && UploadEnclosure(academic_exchange, fileEnc))
                        {
                            //fileid = academic_exchange.NewsID;
                            var img = Request.Files["xdaTanFileImg"];
                            if (img != null && img.ContentLength > 0)
                            {
                                HttpPostedFileBase image = img;
                                //判定文件的大小
                                double dFileSize = image.ContentLength;
                                if (dFileSize > 5242880)//1024*1024*5)
                                {
                                    Response.Write("<script>alert('" + image.FileName + "文件大于5MB')</script>");
                                }
                                else if (dFileSize != 0)
                                {
                                    string timenow = DateTime.Now.ToString("yyyyMMddhhmmss");//得到系统时间
                                    string path = "~/Html/Academics/" + academic_exchange.AcademicID + "/";
                                    //Directory.CreateDirectory(Server.MapPath(path));
                                    //周煜 2017.2.24
                                    //string imgName = "";
                                    //for (int mapLength = 0; mapLength < image.FileName.Length; mapLength++)
                                    //{
                                    //    if (image.FileName[mapLength] == '\\')
                                    //    {
                                    //        imgName = "";
                                    //        continue;
                                    //    }
                                    //    imgName = imgName + image.FileName[mapLength];
                                    //}
                                    string fFullDir = path + "title" + timenow + img.FileName;
                                    image.SaveAs(Server.MapPath(fFullDir));
                                    academic_exchange.PhotoAddress = fFullDir;
                                    db_academic.Update(academic_exchange);
                                }
                            }
                            Response.Write("<script>alert('添加成功,请继续添加附件！')</script>");
                            return PartialView("Upload");
                        }
                        else
                            Response.Write("<script>alert('文件上传失败，请重新上传！')</script>");
                    }
                    else
                        Response.Write("<script>alert('添加失败！')</script>");
                }
            ViewBag.Reload = true;
            ViewBag.Sider = 4;
            return PartialView(academic_exchange);
        }



        public ActionResult Delete(int id)
        {
            Academic_Exchange ae = db_academic.SearchbyId(id);
            if (ae == null)
            {
                return HttpNotFound();
            }
            return PartialView(ae);
        }
        
        //
        // POST: /Academic/Delete/5

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            if (db_academic.Delete(id))
                return RedirectToAction("List");
            else
            {
                Response.Write("<script>alert('删除失败！')</script>");
                Academic_Exchange ae = db_academic.SearchbyId(id);
                return PartialView("Delete", ae);
            }
        }

        [HttpPost]
        public ActionResult MultDelete(FormCollection collection)
        {
            string[] ids = { };
            if (collection.GetValues("checks") != null)//这是判断name为checkboxRole的checkbox的值是否为空，若为空返回NULL;
            {
                string strids = collection.GetValue("checks").AttemptedValue;//AttemptedValue返回一个以，分割的字符串
                ids = strids.Split(',');
                string num = ""; //检查是否删除勾选的
                foreach (string getid in ids)
                {
                    int ID = Convert.ToInt32(getid);
                    if (!db_academic.Delete(ID))
                        num = num + getid + " ";
                }
                if (num.Length > 0)
                    Response.Write("<script>alert('" + num + "删除失败！')</script>");
                else
                    Response.Write("<script>alert('删除成功！')</script>");
            }
            else
                Response.Write("<script>alert('无选中！')</script>");
            return RedirectToAction("DeleteList");
        }

        //
        // GET: /Academic/Edit/5

        public ActionResult Edit(int id = 0)
        {
            Academic_Exchange academic_exchange = db_academic.SearchbyId(id);
            if (academic_exchange == null)
            {
                return HttpNotFound();
            }
            return PartialView(academic_exchange);
        }

        //
        // POST: /Academic/Edit/5

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(Academic_Exchange academic_exchange)
        {
            if (ModelState.IsValid)
            {
                if (db_academic.HasSameAcdemicExchange(academic_exchange))
                {
                    ModelState.AddModelError("AcademicName", "已有同名新闻");

NewRLWeb/Views/Academic/Academic_Exchange_View.cshtml
<!--周煜 2016.11.13-->
@{
    ViewBag.Title = "Academic_Exchange_View";
}
@using NewRLWeb.Models;
@model Academic_Exchange
<!--2016.11.16 周煜-->
@*<h2>Academic_Exchange_View</h2>*@
@Html.ActionLink("返回列表", "Index", new { id=1 },new{style="font-size:25px;margin-left:5%;"})
<section class="contact">
    <div class="page2_news container" style="border: 1px">
        <div>
            <h1 style="margin-left:45%;">@Model.AcademicName</h1>
            <h2 style="margin-left:60%;">@Model.Abstract</h2>
            <br />
            @{
                string filePath = @Model.Coverage;
                filePath = HttpContext.Current.Server.MapPath(filePath);
                string fileContent = string.Empty;
                var reader = filePath;
                StreamReader sr = new StreamReader(reader, System.Text.Encoding.Default);
                fileContent = sr.ReadToEnd();
            }
            @Html.Raw(fileContent)
            <div style="float:right;margin-right:5%;">
                <h1>@Model.BeginTime - @Model.EndTime </h1>
            </div>
        </div>
    </div>
</section>

NewRLWeb/Views/Academic/Create.cshtml
@model NewRLWeb.Models.Academic_Exchange

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Manage.cshtml";/*2017.2.27 BLM加*/

    //if (ViewBag.Reload != null)
    //{
    //    bool isreload = ViewBag.Reload;
    //    if (isreload)
    //    {
    //        Layout = "~/Views/Shared/_Manage.cshtml";
    //    }
    //}
}
<link rel="stylesheet" href="http://code.jquery.com/ui/1.10.3/themes/smoothness/jquery-ui.css">
<script src="~/Scripts/jquery-1.7.1.min.js"></script>
<script src="~/Scripts/jquery-ui-1.8.24.js"></script>
<link rel="stylesheet" href="http://jqueryui.com/resources/demos/style.css">
<link href="~/Content/themes/Black/theme.css" rel="stylesheet" />
<script type="text/javascript">

    //判断浏览器是否支持FileReader接口
    if (typeof FileReader == 'undefined') {
        document.getElementById("xmTanDiv").InnerHTML = "<h1>当前浏览器不支持FileReader接口</h1>";
        //使选择控件不可操作
        document.getElementById("xdaTanFileImg").setAttribute("disabled", "disabled");
    }
    //选择图片，马上预览
    function xmTanUploadImg(obj) {
        var file = obj.files[0];

        console.log(obj); console.log(file);
        console.log("file.size = " + file.size);  //file.size 单位为byte

        var reader = new FileReader();

        //读取文件过程方法
        reader.onloadstart = function (e) {
            console.log("开始读取....");
        }
        reader.onprogress = function (e) {
            console.log("正在读取中....");
        }
        reader.onabort = function (e) {
            console.log("中断读取....");
        }
        reader.onerror = function (e) {
            console.log("读取异常....");
        }
        reader.onload = function (e) {
            console.log("成功读取....");

            var img = document.getElementById("xmTanImg");
            img.src = e.target.result;
            //或者 img.src = this.result;  //e.target == this
        }

        reader.readAsDataURL(file)
    };

    $(function () {
        $("#BeginTime").datepicker();
    });
    $(function () {
        $("#EndTime").datepicker();
    });
</script>
<!--//////////////////////////////////////////////////////周煜 2017.1.15////////////////////////////////////////////////////////////////////-->
@*<script src="/Scripts/jquery-1.7.1.min.js"></script>
    <script src="/Scripts/jquery-ui-1.8.24.js"></script>
    <link rel="stylesheet" href="/resources/demos/style.css" />*@
<div style="height: 520px; position: relative;">
    @using (Html.BeginForm("Create", "Academic", FormMethod.Post, new { enctype = "multipart/form-data" }))
    {   <!--提交表单的一种方式-->
    <!--使用form提交表单-->
        @*<form action="/News/NewsSubmit" enctype="multipart/form-data" method="post" id="newsCreate">*@
        @Html.AntiForgeryToken()
        @Html.ValidationSummary(true)

        <fieldset>
            <legend></legend>

            <div class="row">
                <div class="col-xs-12 col-md-8">
                    <div class="row">

                        <div class="form-group" style="margin-left:15px">
                            @Html.LabelFor(model => model.AcademicName, new { @id = "Title_lab" })
                            @Html.TextBoxFor(model => model.AcademicName, new { @class = "form-control", @required = "required", @maxlength = "20" })
                            @Html.ValidationMessageFor(model => model.AcademicName)
                        </div>

                    </div>
                    <div class="row">
                        <div class="form-group" style="margin-left:15px">
                            @Html.LabelFor(model => model.Abstract, new { @id = "Abstract_lab" })
                            <textarea class="form-control" maxlength="100" required="required" style="resize: none;" data-val="true" data-val-required="您需要填写摘要" id="Abstract" name="Abstract" rows="2"></textarea>
                            @Html.ValidationMessageFor(model => model.Abstract)
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-xs-6">
                            @Html.LabelFor(model => model.BeginTime)
                            @Html.TextBoxFor(model => model.BeginTime, new { @class = "form-control", @required = "required", @maxlength = "20", @id = "BeginTime", @name = "BeginTime" })
                            @*<input data-val="true" data-val-date="字段 开始日期 必须是日期。" data-val-required="开始日期 字段是必需的。" required="required" readonly="readonly" id="BeginTime" name="BeginTime" type="text" value="" class="form-control">*@
                            @Html.ValidationMessageFor(model => model.BeginTime)
                        </div>
                        <div class="col-xs-6">
                            @Html.LabelFor(model => model.EndTime)
                            @Html.TextBoxFor(model => model.EndTime, new { @class = "form-control", @required = "required", @maxlength = "20", @id = "EndTime", @name = "EndTime" })
                            @*<input data-val="true" data-val-date="字段 结束日期 必须是日期。" data-val-required="结束日期 字段是必需的。" required="required" readonly="readonly" id="EndTime" name="EndTime" type="text" value="" class="form-control">*@
                            @Html.ValidationMessageFor(model => model.EndTime)
                        </div>
                    </div>
                </div>
                <div class="col-xs-6 col-md-4">
                    <label for="Pho_Address">学术展示图片</label>
                    <div>
                        <div>
                            <img id="xmTanImg" width="350" height="230" src="~/Images/empty.gif" />
                        </div>
                        @* 2017.03.02 BLM 修改样式 start *@
                        <div class="a-upload">
                            <input type="file" required="required" id="xdaTanFileImg" name="xdaTanFileImg" onchange="xmTanUploadImg(this)" accept="image/*" />选择图片
                            <div id="xmTanDiv"></div>
                        </div>
                        @* 2017.03.02 end *@
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-xs-4 col-sm-6">
                    <label for="Coverage">
                        内容<a style="color:red;"> *请选择相应的HTML文件</a>
                    </label>

                    <!--2017.03.02 BLM start 修改上传按钮样式-->
                    <div class="inputFileWrapper">
                        <label for="FirLoad">
                            <input type="file" name="UpLoadHtm" id="FirLoad" required="required" accept=".htm" />
                            <span class="custorm-style">
                                <span class="left-text" id="leftText"></span>
                                <span class="right-button">浏览...</span>
                            </span>
                        </label>
                    </div>
                    <script>
                        var fileBtn = $("#FirLoad");
                        fileBtn.on("change", function () {
                            var index = $(this).val().lastIndexOf("\\");
                            var sFileName = $(this).val().substr((index + 1));
                            $("#leftText").html(sFileName);
                        });
                    </script>
                    @* <input type="file" required="required" name="UpLoadHtm" id="FirLoad" class="filebtn" accept=".htm" />浏览*@
                    <!--2017.03.02 BLM end-->

                </div>
                <div class="col-xs-4 col-sm-6">
                    <label for="Coverage">
                        附件<a style="color:red;"> *请选择附件(可为空)</a>
                    </label>
                    <div class="inputFileWrapper">
                        <label for="ThrLoad">
                            <input type="file" name="UpLoadEnc" id="ThrLoad" required="required" accept="image/*" />
                            <span class="custorm-style">
                                <span class="left-text" id="Text"></span>
                                <span class="right-button">浏览...</span>
                            </span>
                        </label>
                    </div>
                    <script>
                        var fileBtn = $("#ThrLoad");
                        fileBtn.on("change", function () {
                            var index = $(this).val().lastIndexOf("\\");
                            var sFileName = $(this).val().substr((index + 1));
                            $("#Text").html(sFileName);
                        });
                    </script>
                    @*<input type="file" name="UpLoadEnc" id="ThrLoad" class="filebtn" accept="image/*" />*@
                </div>
            </div>
            <br />
            <div class="row">
                <div class="col-xs-12 col-md-8">
                    <div class="form-group">
                        @Html.LabelFor(model => model.Link)
                        @Html.TextBoxFor(model => model.Link, new { @class = "form-control", @placeholder = "请输入网址" })
                        @Html.ValidationMessageFor(model => model.Link)
                    </div>
                </div>
            </div>
            <p>
                <input type="submit" @*onclick="create_submit()"*@ value="确定" name="Create" style="right: 17%; position: absolute; bottom: 0; " />
            </p>
        </fieldset>
    }
</div>
<div>
    @Html.ActionLink("返回", "List")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

NewRLWeb/Views/Academic/Delete.cshtml
@model NewRLWeb.Models.Academic_Exchange

@{
    ViewBag.Title = "Delete";
    //Layout = "~/Views/Shared/_Manage.cshtml";
}
@using (Html.BeginForm("Delete", "Academic", FormMethod.Post))
{
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true)
    <fieldset>
        <legend>确定删除该学术交流信息?</legend>

        <div class="row">
            <div class="col-xs-12 col-md-8">
                <div class="row">

                    <div class="form-group" style="margin-left:15px">
                        @Html.LabelFor(model => model.AcademicName)
                        @Html.TextBoxFor(model => model.AcademicName, new { @class = "form-control", @readonly = "readonly" })
                    </div>

                </div>
                <div class="row">
                    <div class="form-group" style="margin-left:15px">
                        @Html.LabelFor(model => model.Abstract)
                        <textarea class="form-control" readonly="readonly" style="resize: none;" data-val="true" data-val-required="您需要填写摘要" id="Abstract" name="Abstract" rows="2">@Model.Abstract</textarea>
                    </div>
                </div>
                <div class="row">
                    <div class="col-xs-6">
                        @Html.LabelFor(model => model.BeginTime)
                        <input data-val="true" data-val-date="字段 开始日期 必须是日期。" data-val-required="开始日期 字段是必需的。" readonly="readonly" id="BeginTime" name="BeginTime" type="text" value="@Model.BeginTime.ToShortDateString()" class="form-control">
                    </div>
                    <div class="col-xs-6">
                        @Html.LabelFor(model => model.EndTime)
                        <input data-val="true" data-val-date="字段 结束日期 必须是日期。" data-val-required="结束日期 字段是必需的。" readonly="readonly" id="EndTime" name="EndTime" type="text" value="@Model.EndTime.ToShortDateString()" class="form-control">
                    </div>
                </div>
            </div>
            <div class="col-xs-6 col-md-4">
                <label for="Pho_Address">学术展示图片</label>
                <div>
                    <div>
                        @if (string.IsNullOrWhiteSpace(Model.PhotoAddress))
                        {
                            <img id="xmTanImg" width="350" height="230" src="~/Images/empty.gif" />
                        }
                        else
                        {
                            <img id="xmTanImg" width="350" height="230" src="@Url.Content(Model.PhotoAddress)" alt="images" />
                            <div style="display:none">
                                @Html.EditorFor(model => model.PhotoAddress)
                            </div>
                        }
                    </div>
                </div>
            </div>
        </div>
        @if (!string.IsNullOrWhiteSpace(Model.Link))
        {
            <div class="row">
                <div class="col-xs-12 col-md-8">
                    <div class="form-group">
                        @Html.LabelFor(model => model.Link)
                        @Html.TextBoxFor(model => model.Link, new { @class = "form-control", @readonly = "readonly" })
                    </div>
                </div>
            </div>
        }
        <br />
        <p>
            <input type="submit" value="删除" />
        </p>

    </fieldset>
    <p>
        @Html.ActionLink("返回", "List")
    </p>
}

NewRLWeb/Views/Academic/DeleteTable.cshtml
@model IEnumerable<NewRLWeb.Models.Academic_Exchange>

@{
    ViewBag.Title = "DeleteList";
    //Layout = "~/Views/Shared/_Manage.cshtml";
}

<script>
    $("#chkAll").click(function () {
        if (this.checked) {
            $("input[name='checks']").each(function () { this.checked = true; });
        }
        else {
            $("input[name='checks']").each(function () { this.checked = false; });
        }
    });
</script>
<!--周煜2017.1.15-->


@*<p>
    @Html.ActionLink("Create New", "Create")
</p>*@


<div style="height: 480px; position: relative;">
    @using (Html.BeginForm("MultDelete", "Academic", FormMethod.Post))
    {
        <table class="table table-hover">
            <tr>
                <th>
                    <input type="checkbox" id="chkAll" />全选
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.AcademicName)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Abstract)
                </th>
                @*<th>
                    @Html.DisplayNameFor(model => model.Coverage)
                </th>*@
                <th>
                    @Html.DisplayNameFor(model => model.BeginTime)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.EndTime)
                </th>
                <th></th>
            </tr>

            @foreach (var item in Model)
            {
                <tr>
                    <td>
                        <input type="checkbox" id="checks" name="checks" value="@item.AcademicID" />
                    </td>
                    <td>
                        @*@Html.DisplayFor(modelItem => item.AcademicName)*@
                        @UIHelper.StrSub(item.AcademicName, 20)
                    </td>
                    <td>
                        @*@Html.DisplayFor(modelItem => item.Abstract)*@
                        @UIHelper.StrSub(item.Abstract,25)
                    </td>
                    @*<td>
                        @Html.DisplayFor(modelItem => item.Coverage)
                    </td>*@
                    <td>
                        @Html.DisplayFor(modelItem => item.BeginTime)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.EndTime)
                    </td>
                </tr>
            }

        </table>
    <input type="submit" name="BtnDelete" value="删除" style="right: 13%; position: absolute; bottom: -10%; " />
    }
</div>

NewRLWeb/Views/Academic/Details.cshtml
@model NewRLWeb.Models.Academic_Exchange

@{
    ViewBag.Title = "Details";
}

<div style="height: 520px; position: relative;">
    <fieldset>
        <legend></legend>

        <div class="row">
            <div class="col-xs-12 col-md-8">
                <div class="row">

                    <div class="form-group" style="margin-left:15px">
                        @Html.LabelFor(model => model.AcademicName)
                        @Html.TextBoxFor(model => model.AcademicName, new { @class = "form-control", @readonly = "readonly" })
                    </div>

                </div>
                <div class="row">
                    <div class="form-group" style="margin-left:15px">
                        @Html.LabelFor(model => model.Abstract)
                        <textarea class="form-control" readonly="readonly" style="resize: none;" data-val="true" data-val-required="您需要填写摘要" id="Abstract" name="Abstract" rows="2">@Model.Abstract</textarea>
                    </div>
                </div>
                <div class="row">
                    <div class="col-xs-6">
                        @Html.LabelFor(model => model.BeginTime)
                        <input data-val="true" data-val-date="字段 开始日期 必须是日期。" data-val-required="开始日期 字段是必需的。" readonly="readonly" id="BeginTime" name="BeginTime" type="text" value="@Model.BeginTime.ToShortDateString()" class="form-control">
                    </div>
                    <div class="col-xs-6">
                        @Html.LabelFor(model => model.EndTime)
                        <input data-val="true" data-val-date="字段 结束日期 必须是日期。" data-val-required="结束日期 字段是必需的。" readonly="readonly" id="EndTime" name="EndTime" type="text" value="@Model.EndTime.ToShortDateString()" class="form-control">
                    </div>
                </div>
            </div>
            <div class="col-xs-6 col-md-4">
                <label for="Pho_Address">学术展示图片</label>
                <div>
                    <div>
                        @if (string.IsNullOrWhiteSpace(Model.PhotoAddress))
                        {
                            <img id="xmTanImg" width="350" height="230" src="~/Images/empty.gif" />
                        }
                        else
                        {
                            <img id="xmTanImg" width="350" height="230" src="@Url.Content(Model.PhotoAddress)" alt="images" />
                            <div style="display:none">
                                @Html.EditorFor(model => model.PhotoAddress)
                            </div>
                        }
                    </div>
                </div>
            </div>
        </div>
        @if (!string.IsNullOrWhiteSpace(Model.Link))
        {
            <div class="row">
                <div class="col-xs-12 col-md-8">
                    <div class="form-group">
                        @Html.LabelFor(model => model.Link)
                        @Html.TextBoxFor(model => model.Link, new { @class = "form-control", @readonly = "readonly" })
                    </div>
                </div>
            </div>
        }

    </fieldset>
</div>
<p>
    @Ajax.ActionLink("编辑", "Edit", "Academic", new { id = Model.AcademicID }, new AjaxOptions() { UpdateTargetId = "mainContent", HttpMethod = "Get", OnBegin = "active", InsertionMode = InsertionMode.Replace }) |
    @Html.ActionLink("返回", "List", "Academic")
</p>